-   id: nbstripout
    name: nbstripout
    description: 'strip output from Jupyter and IPython notebooks'
    entry: nbstripout
    language: python
    language_version: python3
    require_serial: true
    files: \.ipynb$
